### ISSUE TITLE
DS3 - Color Variables

### ISSUE THREAD

**Issue by Hendrik-Pils** [kevinldg/reuse-app#46]
## Value proposition

As a developer
I want to organize the app's primary and secondary colors as variables in the styles.css
In order to clean up the app and to have a better overview.

## Acceptance criteria

- [ ] In the styles.css, all necessary colors are defined.
- [ ] In the components, where the corresponding colors are needed, var(--) is used.

## Tasks

- [ ] Define the colors in the styles.css.
- [ ] Change the colors with (var--) in every component.
